/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}', './App.tsx'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: '#f8f9fa',
          dim: '#d9dadb',
          bright: '#f8f9fa',
          'container-lowest': '#ffffff',
          'container-low': '#f3f4f5',
          container: '#edeeef',
          'container-high': '#e7e8e9',
          'container-highest': '#e1e3e4',
          tint: '#3f6653',
          variant: '#e1e3e4',
        },
        'on-surface': {
          DEFAULT: '#191c1d',
          variant: '#414844',
        },
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        outline: {
          DEFAULT: '#717973',
          variant: '#c1c8c2',
        },
        primary: {
          DEFAULT: '#012d1d',
          container: '#1b4332',
          fixed: '#c1ecd4',
          'fixed-dim': '#a5d0b9',
        },
        'on-primary': {
          DEFAULT: '#ffffff',
          container: '#86af99',
          fixed: '#002114',
          'fixed-variant': '#274e3d',
        },
        'inverse-primary': '#a5d0b9',
        secondary: {
          DEFAULT: '#7d562d',
          container: '#ffca98',
          fixed: '#ffdcbd',
          'fixed-dim': '#f0bd8b',
        },
        'on-secondary': {
          DEFAULT: '#ffffff',
          container: '#7a532a',
          fixed: '#2c1600',
          'fixed-variant': '#623f18',
        },
        tertiary: {
          DEFAULT: '#002d1c',
          container: '#00452e',
          fixed: '#b1f0ce',
          'fixed-dim': '#95d4b3',
        },
        'on-tertiary': {
          DEFAULT: '#ffffff',
          container: '#75b393',
          fixed: '#002114',
          'fixed-variant': '#0e5138',
        },
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
        },
        'on-error': {
          DEFAULT: '#ffffff',
          container: '#93000a',
        },
        background: '#f8f9fa',
        'on-background': '#191c1d',
        status: {
          healthy: '#2d6a4f',
          disease: '#ba1a1a',
          warning: '#d4a373',
        },
      },
      fontFamily: {
        'hanken': ['HankenGrotesk'],
        'hanken-bold': ['HankenGrotesk_700Bold'],
        'hanken-semibold': ['HankenGrotesk_600SemiBold'],
        'inter': ['Inter'],
        'inter-medium': ['Inter_500Medium'],
        'jetbrains': ['JetBrainsMono'],
        'jetbrains-medium': ['JetBrainsMono_500Medium'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500', letterSpacing: '0.02em' }],
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        full: '9999px',
      },
      spacing: {
        'base': '8px',
        'container-padding': '20px',
        'gutter': '16px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'touch-target': '48px',
      },
    },
  },
  plugins: [],
};
